version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
      time: "12:00" # UTC
    reviewers:
      - "SoMuchFonSubtlety"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "12:00" # UTC
    reviewers:
      - "SoMuchFonSubtlety"

